### PR TITLE
Update rmd fragments post with method that works

### LINKED ISSUE #55: Rmd hunks
Thanks again for your post about re-usable Rmd pieces @gadenbuie! 

I'd have left a comment if I could, so [yes you're missing out](https://twitter.com/grrrck/status/1179379856196489216) (just kidding).

Compared to your post, I now put re-usable Rmd pieces under man/rmdhunks/ see for instance https://github.com/lockedata/hubspot that passes R CMD check and whose pkgdown website looks fine.

Downsides to keeping pieces under vignettes/ : pieces not available during R CMD check, and pkgdown builds them as unnamed articles.

See also https://github.com/r-hub/blog/pull/44

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #55

### CODE REVIEW

**Comment by gadenbuie** [comment]
@maelle Do you mind taking a quick look at what I added to the top of the post to make sure I got it right? [preview here](https://5de7ce8e945adc000820d980--garrickadenbuie.netlify.com/blog/dry-vignette-and-readme/)

**Comment by maelle** [comment]
Thanks, it looks great! (Note that my two packages using the hack are not on CRAN yet) I just wonder whether you could make the update metadata less visible? Because now the post starts by mentioning Rmd fragments w/o introducing them which might be puzzling?

Two things that come to mind and that you could mention
- having fragments also means it is easier to shuffle content within the same Rmd document.
- roxygen2 `@includeRmd`

**Comment by gadenbuie** [comment]
Thanks @maelle that makes a lot of sense. I folded the update into the post.

Let me know if those packages make it onto CRAN or if you find another package that does this _and_ is on CRAN. It'd be nice to follow up with a post about that. I'll wait for an future post to mention the roxygen2 method, too.

Thanks again for all your help!

**Comment by maelle** [comment]
Yay, thank _you_! And of course reg following up.

**Pull request merged**
